services:
    app:
        container_name: app_fastapi
        build:
            context: .
            dockerfile: .\dockerfiles\back.dockerfile
        ports:
            - 8000:8000
        depends_on:
            - db
        command: sh -c "alembic upgrade head && gunicorn servidor.config:app --workers=1 --worker-class=uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 --access-logfile=-"
    db:
        container_name: db_postgres
        image: postgres:16.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
    pgadmin:
        container_name: pg_admin
        image: dpage/pgadmin4:latest
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - 5050:80
