services:
    app:
        build:
            context: .
            dockerfile: .\dockerfiles\back.dockerfile
        ports:
            - 8000:8000
    db:
        image: postgres:16.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - 5050:80
