"""adicionando mais indices

Revision ID: a22ad1911315
Revises: a772483863b2
Create Date: 2024-09-06 14:55:30.540513

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a22ad1911315"
down_revision: Union[str, None] = "a772483863b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_historicos_id_usuario_id", "historicos", ["id", "usuario_id"], unique=False
    )
    op.create_index(
        "idx_historicos_lancamento_id", "historicos", ["lancamento_id"], unique=False
    )
    op.create_index(
        "idx_historicos_usuario_id", "historicos", ["usuario_id"], unique=False
    )
    op.create_index(
        "idx_lancamentos_recorrentes_id_usuario_id",
        "lancamentos_recorrentes",
        ["id", "usuario_id"],
        unique=False,
    )
    op.create_index(
        "idx_lancamentos_recorrentes_inicia_em_termina_em",
        "lancamentos_recorrentes",
        ["inicia_em", "termina_em"],
        unique=False,
    )
    op.create_index(
        "idx_lancamentos_recorrentes_usuario_id",
        "lancamentos_recorrentes",
        ["usuario_id"],
        unique=False,
    )
    op.create_index("idx_usuarios_email", "usuarios", ["email"], unique=False)
    op.create_index("idx_usuarios_nome", "usuarios", ["nome"], unique=False)
    op.create_index("idx_usuarios_token", "usuarios", ["token"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_usuarios_token", table_name="usuarios")
    op.drop_index("idx_usuarios_nome", table_name="usuarios")
    op.drop_index("idx_usuarios_email", table_name="usuarios")
    op.drop_index(
        "idx_lancamentos_recorrentes_usuario_id", table_name="lancamentos_recorrentes"
    )
    op.drop_index(
        "idx_lancamentos_recorrentes_inicia_em_termina_em",
        table_name="lancamentos_recorrentes",
    )
    op.drop_index(
        "idx_lancamentos_recorrentes_id_usuario_id",
        table_name="lancamentos_recorrentes",
    )
    op.drop_index("idx_historicos_usuario_id", table_name="historicos")
    op.drop_index("idx_historicos_lancamento_id", table_name="historicos")
    op.drop_index("idx_historicos_id_usuario_id", table_name="historicos")
    # ### end Alembic commands ###
