"""adicionando usuario a categoria

Revision ID: a772483863b2
Revises: 35573f1b667c
Create Date: 2024-09-06 14:26:34.914036

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a772483863b2"
down_revision: Union[str, None] = "35573f1b667c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categorias", sa.Column("usuario_id", sa.UUID(), nullable=True))
    op.drop_constraint("categorias_nome_key", "categorias", type_="unique")
    op.create_index("idx_categorias_nome", "categorias", ["nome"], unique=False)
    op.create_index(
        "idx_categorias_usuario_id", "categorias", ["usuario_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_categoria_nome_usuario_id", "categorias", ["nome", "usuario_id"]
    )
    op.create_foreign_key(None, "categorias", "usuarios", ["usuario_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categorias", type_="foreignkey")
    op.drop_constraint("uq_categoria_nome_usuario_id", "categorias", type_="unique")
    op.drop_index("idx_categorias_usuario_id", table_name="categorias")
    op.drop_index("idx_categorias_nome", table_name="categorias")
    op.create_unique_constraint("categorias_nome_key", "categorias", ["nome"])
    op.drop_column("categorias", "usuario_id")
    # ### end Alembic commands ###
