"""criando campo nome em historico

Revision ID: b67bba96423f
Revises: f8261c963e0f
Create Date: 2024-07-26 21:23:04.609535

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b67bba96423f"
down_revision: Union[str, None] = "f8261c963e0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("historicos", sa.Column("nome", sa.String(), nullable=True))
    op.add_column(
        "lancamentos_recorrentes", sa.Column("nome", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lancamentos_recorrentes", "nome")
    op.drop_column("historicos", "nome")
    # ### end Alembic commands ###
